Feat/scroll to error
Shelf-nu/shelf.nu pull request #1035
Opened 2024-06-08 13:31 UTC by Bhavyajain21

/claim #1018 
/fixes #1018

2024-06-10 09:55 UTC, DonKoko requested changes
Overall good, but I have some comments:

- [x] I don't like that we have to pass the `onSubmit` to the form. What I would rather do is create our own Form component that just re-exports the Form from remix by passing this handler. This way we do have to change the imports everywhere, but that's just a 1 time task. We don't have to think about it every time, we use the Form component as it will be automatically managed.
- [ ] The scrolling currently scrolls directly to the field. There should be an offset so it field doesn't stick directly to the top of the browser. See screenshot. This shouldn't happen
<img width="1058" alt="Screenshot 2024-06-10 at 12 50 44" src="https://github.com/Shelf-nu/shelf.nu/assets/7840007/a39dee96-2092-487d-b73a-b0bae06b2ba4">

- [ ] currently the scrolling happens even if the field is already on the dom. The idea was that we use the `intersectionObserver` so we only add the event handler for inputs that are not visible in the viewport.

- [ ] In general, using `document.querySelectorAll` in react is not recommended. This is not the highest priority but I would like to give it a try. So I think that if we have our own Form component we can use the form ref to access the children of the form and search them, instead of having to access the dom using document.selector. If that doesn't work you have to do some extra checks to make sure that document is available as I think this will cause hydration errors as we have no document on server so the onSubmit value will be different on client and server

2024-06-10 09:55 UTC, DonKoko commented on app/utils/scroll-to-error.ts
> +  const observer = new IntersectionObserver(
I am having trouble to understand how this works. I see the observer and I understand that part but how does it interact with `scrollToError`. Seems like scroll will always be called on all entries, not just one the ones that are not visible.

Also please update this code by adding comments how it works, it needs to be more clear to developers who have to use and interact with this.

2024-06-10 13:55 UTC, Bhavyajain21 commented on app/utils/scroll-to-error.ts
> +  const observer = new IntersectionObserver(
Hey @DonKoko , I have updated this method to scroll only to fields if it isn't visible in the viewport. Have added few comments as well.

2024-06-11 07:31 UTC, DonKoko reviewed
Added some comments and made some changes myself that I pushed. There is still some stuff pending like the form name.

2024-06-11 07:31 UTC, DonKoko commented on app/components/CustomForm.tsx
> +export const CustomForm = React.forwardRef<HTMLFormElement, CustomFormProps>(
We should call it just `Form`. Logically its a custom form but for us in shelf, its our main form. And I know we can do a named import with "as" but that adds overhead. With vscode you can just click cmd+. and it will auto import. I dont want to have to manually adjust the imports every time I need to use the form.

2024-06-11 07:31 UTC, DonKoko commented on app/components/CustomForm.tsx
File name is not following our convention. Should be `custom-form.tsx`

2024-06-11 07:31 UTC, DonKoko commented on app/components/CustomForm.tsx
> +  (props, ref) => <RemixForm ref={ref} {...props} onSubmit={scrollToError} />
Here we have an issue. If the form already has an onSubmit function? I think it needs to be something like:
```ts
onSubmit={(v) => {
  onSubmit(v);
  scrollToError()
}}
```

So if the developer using the form is already passing an onSubmit function it runs.

2024-06-11 07:31 UTC, DonKoko commented on app/components/CustomForm.tsx
> +type HTMLFormMethod = "post" | "get" | undefined;
I dont think you need those custom types. You can just use the RemixFormProps instead. I did some testing and some changes(except component name) and came to this:
```ts
import React from "react";
import {
  Form as RemixForm,
  type FormProps as RemixFormProps,
} from "@remix-run/react";
import { scrollToError } from "~/utils/scroll-to-error";

export const CustomForm = React.forwardRef<HTMLFormElement, RemixFormProps>(
  (props, ref) => (
    <RemixForm
      ref={ref}
      {...props}
      onSubmit={(v) => {
        scrollToError();
        props?.onSubmit?.(v);
      }}
    />
  )
);

CustomForm.displayName = "CustomForm";
```

2024-06-11 10:17 UTC, Bhavyajain21 commented on app/components/CustomForm.tsx
> +export const CustomForm = React.forwardRef<HTMLFormElement, CustomFormProps>(
Fixed!

2024-06-11 10:17 UTC, Bhavyajain21 commented on app/components/CustomForm.tsx
Fixed!

2024-06-11 10:18 UTC, Bhavyajain21 commented on app/components/CustomForm.tsx
> +  (props, ref) => <RemixForm ref={ref} {...props} onSubmit={scrollToError} />
Fixed by you!!

2024-06-11 10:19 UTC, Bhavyajain21 commented on app/components/CustomForm.tsx
> +type HTMLFormMethod = "post" | "get" | undefined;
Resolved

2024-06-11 13:12 UTC, merged