Feature: 1068 Add a custom asset ID field
Shelf-nu/shelf.nu pull request #1078
Opened 2024-06-19 15:30 UTC by Teraskull

Hi! This is my attempt at being useful.

First of all, thank you for this amazing software. The best UI among all existing inventory management systems.

__Full disclosure__: I am a backend dev and have little experience in frontend. This is the first time I'm touching Remix and React.

I do not expect this PR to be merged, this is only to show the general UX of the custom Asset ID feature.

This is a rough naive working PoC for #1068 that adds an optional and unique `propertyId` field to the `Asset` table.

This PR misses a lot of implementation details, types, and does not account for a lot of places where the code should be updated.

### Notes:

* I named the field `propertyId` to avoid confusion with Asset ID. It can be renamed to whatever fits best.
* The position of the asset text field also does not matter.
* If you duplicate an asset that has a Property ID, the duplicate will not have a Property ID set.
* If no property ID is set, the "Property ID" filed in the asset details will not be shown.
* Updated the `searchVector` to search by `propertyId`.
* Added a Property column to the `/assets` page. It's completely optional because it takes up a lot of space.
* I added a `/property/$propertyId` page that redirects to the corresponding asset page if it exists. Otherwise show an "Asset not found" page. The route name is also an example, can be whatever.
* This redirect feature is pretty important since we can make our own QR Code scanner that redirects to an asset page, using an existing ID from our asset stickers.

### Known Issues:

* Creating/editing/duplicating assets with a `propertyId` is handled. I have no idea what other processes are affected.
* The field is unique, and if you try creating an asset with a duplicate `propertyId` it will throw a hardcoded `maybeUniqueConstraintViolation` error that says "Asset __name__ is already taken".

![image](https://github.com/Shelf-nu/shelf.nu/assets/24798198/964259db-04d1-43c9-9520-1e561bfc8151)

### Screenshots of the feature:

On the list of assets:

![image](https://github.com/Shelf-nu/shelf.nu/assets/24798198/40453c53-7ca3-4e1a-a793-f58928e837ed)

Creating/editing an asset:

![image](https://github.com/Shelf-nu/shelf.nu/assets/24798198/c4cc6a7a-ed85-4da7-ab2d-8d32d8fd4368)

On the asset page:

![image](https://github.com/Shelf-nu/shelf.nu/assets/24798198/0fc8cf3c-421d-41d1-a4a1-615947c47042)

Overall, this does not look like a big feature to implement, I'm just unfamiliar with the codebase and the general flow.

Thanks!

2024-06-19 16:18 UTC, carlosvirreira commented
Amazing @Teraskull we are super grateful that you took the time to submit a POC we have a scheduled discussion for it tomorrow on our Discord to provide some more info from our end. 

You rock! Thank you!

2024-06-19 16:21 UTC, Teraskull commented
Thanks a lot! I appreciate it @carlosvirreira 

Would be super great if the QR Code block on the asset page gets hidden if an alternative ID is set, since the original ID will not be used for stickers anyways.

2024-06-20 07:48 UTC, DonKoko requested changes
Thanks for opening the PR and doing such a high quality job at your first attempt. It is really appreciated.
I have done a first run through the code and added some comments of small things I noticed, but overall your PR is great. 
It covers most stuff and keeps consistent with our coding manners so that's amazing.

We haven't had the time yet to discuss this internally but I will try to address the points in your proposal that I feel need addressing:

> I named the field propertyId to avoid confusion with Asset ID. It can be renamed to whatever fits best.

I think its a great name. I can't think of anything better right now. Will let you know if it needs updating

> If you duplicate an asset that has a Property ID, the duplicate will not have a Property ID set.
> If no property ID is set, the "Property ID" filed in the asset details will not be shown.
> Updated the searchVector to search by propertyId.

Great 🤟🏼

> Added a Property column to the /assets page. It's completely optional because it takes up a lot of space.

I personally like it and don't think its a problem, but I think it depends on how commonly used it will be by our users. We are planning to soon work on a feature that allows you to choose which columns to show, so once we have that it will be even less of an issue.

> This redirect feature is pretty important since we can make our own QR Code scanner that redirects to an asset page, using an existing ID from our asset stickers.

I agree the redirect is great. Still I would love to hear a bit more how you are planning to use that. Very curious.

> Creating/editing/duplicating assets with a propertyId is handled. I have no idea what other processes are affected.

I think you handled a lot of the important cases. I will think about what we are missing but off the top of my head, 2 things that are quite important:
- Asset imports
- Backup exports & backup imports

The field should be handled in those cases as well. Its just a string field so it should be pretty straightforward to add.

> The field is unique, and if you try creating an asset with a duplicate propertyId it will throw a hardcoded `maybeUniqueConstraintViolation` error that says "Asset name is already taken".

Yeah I understand what you mean. Its just kind of hardcoded, as its currently meant to handle just a singular field per model called name. We would need to adjust how `maybeUniqueConstraintViolation` to be able to show the correct error.


This is my feedback for now. Lets address the points from above and once we discuss it internally, we will let you know if any further adjustments are needed.

2024-06-20 07:48 UTC, DonKoko commented on app/components/assets/form.tsx
> +              Specify the property ID of your asset.
I think we should add some more info about this. Like what is the purpose of this field. I think some of our users might be confused especially if they are not familiar with the terminology.

2024-06-20 07:48 UTC, DonKoko commented on app/components/assets/form.tsx
> +  propertyId: z.string().transform((val) => val.trim()),
Doesn't this make it required? This field should be optional.

2024-06-20 07:48 UTC, DonKoko commented on app/modules/asset/service.server.ts
> +export async function getAssetByPropertyId<T extends Prisma.AssetInclude | undefined>({
🤟🏼

2024-06-20 07:48 UTC, DonKoko commented on app/routes/_layout+/assets.$assetId.overview.tsx
> +              {asset?.propertyId ? (
Indentation is broken. Make sure you use prettier so your formatting is consistent with our codebase. Also when you run the commit message, our post-commit hooks should also fix the formatting so you can also do it this way.

2024-06-20 07:48 UTC, DonKoko commented on app/routes/_layout+/property.$propertyId.tsx
> +export default function Property() {
You dont need a default export here. This is basically a "resource" route that will just handle the redirection.

2024-06-20 07:48 UTC, DonKoko commented on app/routes/_layout+/property.$propertyId.tsx
> +      include: {},
No need to pass the empty object.

2024-06-20 08:40 UTC, DonKoko commented on app/routes/_layout+/property.$propertyId.tsx
Something I realized here when discussing it with Carlos. This will work however, we have to consider the same flow we have when scanning a normal QR. There are quite some edge cases to be handled like when users are logged in or not, whether they have access to that code and so on. We need to handle all the same cases here.

2024-06-20 09:06 UTC, DonKoko commented
@carlosvirreira Something we should already prepare is an article on our knowledge base on how the `propertyId` works and how users can use the custom url to redirect to an asset. I think a lot of users would love this feature. Once we have a link for this article, even if its not published yet, we can add it to the sub title of the field label.

2024-06-20 10:23 UTC, carlosvirreira commented
> @carlosvirreira Something we should already prepare is an article on our knowledge base on how the `propertyId` works and how users can use the custom url to redirect to an asset. I think a lot of users would love this feature. Once we have a link for this article, even if its not published yet, we can add it to the sub title of the field label.

We absolutely 100% will add to marketing site. I will pre-make the page and send the url here.

2024-07-16 16:21 UTC, carlosvirreira commented
> @carlosvirreira Something we should already prepare is an article on our knowledge base on how the `propertyId` works and how users can use the custom url to redirect to an asset. I think a lot of users would love this feature. Once we have a link for this article, even if its not published yet, we can add it to the sub title of the field label.

Here it is : https://www.shelf.nu/knowledge-base/understanding-and-using-custom-property-ids-in-shelf 

Let me know if amendments need be made to the kb article

2024-08-30 14:49 UTC, DonKoko commented
Closing due to inactivity. Feel free to re-open the PR when you want to resume this.

2024-08-30 14:49 UTC, closed without merging