Created profile page for team's registered users
Shelf-nu/shelf.nu pull request #1236
Opened 2024-08-09 11:38 UTC by hunar1312

resolves #729

2024-08-13 08:31 UTC, DonKoko requested changes
Wrote some comments in the code.

2024-08-13 08:31 UTC, DonKoko commented on app/components/workspace/users-actions-dropdown.tsx
> +              to="#"
This should not have the `to` as it will make it behave like a link. We don't want that.

2024-08-13 08:31 UTC, DonKoko commented on app/components/workspace/users-actions-dropdown.tsx
> +        <DropdownMenuTrigger className="size-6 w-full pr-2 outline-none focus-visible:border-0">
I am not a fan of this implementation tbh. I would rather we make the component receive an optional component to be used as a trigger as thats basically the exception. Then in the place where we need a custom button we can pass it when rendering `<TeamUsersActionsDropdown/>`

2024-08-13 08:31 UTC, DonKoko commented on app/routes/_layout+/bookings.tsx
> +  includeBulkActions?: boolean;
Again, the same. If this is true by default, then it should be managed the other way around. The prop should be called `disableBulkActions` and should be false by default.

2024-08-13 08:31 UTC, DonKoko commented on app/routes/_layout+/bookings.tsx
> +    currentRoute?.handle?.name === "$assetId.bookings" ||
At this point that we have 4 options, its better to create an array with the options and use `.includes()`

2024-08-13 08:31 UTC, DonKoko commented on app/routes/_layout+/settings.team.users.$userId.assets.tsx
> +const AssetsList = () => {
I am a bit confused here. The idea was to just import the `AssetsList` from the asset index, so we use the same component. Not sure why you added it here again? assets index already exports this component.

2024-08-13 09:27 UTC, hunar1312 commented on app/routes/_layout+/settings.team.users.$userId.assets.tsx
> +const AssetsList = () => {
Few reasons for a custom asset list: 
1. Different custom empty state
2. Removing teamMember filter and it's dropdown as well
3. To remove sorting filters
4. Different Navigate parameter

@DonKoko maybe we can remove the ListAssetContent and import that from assets Index

2024-08-13 11:25 UTC, DonKoko commented on app/routes/_layout+/settings.team.users.$userId.assets.tsx
> +const AssetsList = () => {
Yeah then all those things need to be adjusted. Still repeating the 90% same code 2 times will create more issues here.

> 1. Different custom empty state

Allow the AssetIndex component to receive the empty state and drill it down to the list

> Removing teamMember filter and it's dropdown as well

I believe we already have ways to do that. Again u can add an optional prop for it.

> To remove sorting filters

You can leave those. They should be in the design. I dont know why they are not.

> Not sure what you mean

Again, this is something that can be passed as props

2024-08-13 11:31 UTC, DonKoko commented
@hunar1312 something i noticed. cmd + click on the users asset index fails. Most likely due to how navigate it used.

2024-08-15 11:24 UTC, DonKoko approved these changes

2024-08-15 11:25 UTC, merged