Bug 1184 date issue fix
Shelf-nu/shelf.nu pull request #1249
Opened 2024-08-14 16:23 UTC by rajeshj11

2024-08-14 16:25 UTC, rajeshj11 commented
@DonKoko can you please review these changes

2024-08-19 07:55 UTC, DonKoko requested changes
Again, you did a lot of changes to the functions that format our date without needing to do them. We do exactly the same for bookings form and then displaying the bookings date on the index for example. You dont need to add any new features or handle any new case. Just need to implement it 1:1 like in bookings.

2024-08-19 07:55 UTC, DonKoko commented on app/utils/custom-fields.ts
> +      return `${year}-${month.padStart(2, "0")}-${day.padStart(2, "0")}`;
We don't do that. The idea is that the formatting is done based on the user locale and timezone. That is what our dateformatters do. You are formatting the date and then hardcoding a different format that doesnt fit with our app.

Here are some examples. My PC has dates in american style:

![image](https://github.com/user-attachments/assets/b12e9837-485a-4fc2-9ce5-922af9c13ced)
![image](https://github.com/user-attachments/assets/b4c8ded6-d7f7-48e4-9534-9df226aa6225)
![image](https://github.com/user-attachments/assets/f699f356-3f40-41dd-a8af-ab01b62d40f1)

As you can see they follow the same format everywhere, except the 1 place where we have the custom field where you are hardcoding the value.

2024-08-20 15:08 UTC, rajeshj11 commented
closing this pr as it is resovled in #1268

2024-08-20 15:08 UTC, closed without merging