feat:show table in mobile with hscroll
Shelf-nu/shelf.nu pull request #1273
Opened 2024-08-21 12:10 UTC by rajeshj11

/closes #969 
showing the table and providing the horizontal scroll if any overflow is there.

Impact: mobile device will able to view the table data.

2024-08-21 13:19 UTC, DonKoko commented
@carlosvirreira Rajesh has taken on this issue. He has updated all tables in the platform to make them horizontally scrollable so users can see full data.
I am deploying it to staging: https://github.com/Shelf-nu/shelf.nu/actions/runs/10490727074

Lets do some testing to make sure everything is okey.

2024-08-21 14:06 UTC, DonKoko requested changes
Writing some feedback, based on what we discussed:

- [x] Some `<Td>` components have `className="table-cell"`. This does nothing as they are already table cells. Lets remove it
- [x] With the new approach the name column(first column) should not grow anymore(only mobile). It should just shrink to the content. Basically default table functionality. This is the case on some pages (assets) but not the case on the bookings index. Should be consistent. Also please check all indecies because in the categories index, for example, the description column grows. Again we dont want that on mobile, just desktop.
- [x] The gradient is a bit too thin(change to 35px). Also the gradient at the left point has to be 100% transparent so we have a smooth transition. Now it looks like a cut-off line
- [x] The gradient should only be there if the table is overflowing horizontally(both desktop and mobile). For example in the Non-registered members index, there are very few columns so they fit and there is no horizontal scroll, however there is still a gradient covering the right column
- [ ] team/users index still has the chevrons, even tho it has the new style of table. Needs to be adjusted
- [ ] Booking/manage-assets modal is basically broken now. I cant scroll it or view it. Same for location/manage-assets modal.

2024-08-21 15:34 UTC, carlosvirreira commented
- [ ] Batch Action is broken on Mobile (Safari) - On Asset Index it works well

Perhaps adjacently related:

On asset dashboard - some widgets seem to assume they are side-scroll-able and therefore show some sort of shadow on the right side.

Same as locations on mobile. Action panel looks broken. 

Calendar component also seems to be cracking.

User table on mobile seems to also show the right pointing chevron to show its click-able but also sidescroll.

@DonKoko my comments.

2024-08-21 19:30 UTC, rajeshj11 commented
> Writing some feedback, based on what we discussed:
> 
> * [ ]  Some `<Td>` components have `className="table-cell"`. This does nothing as they are already table cells. Lets remove it
> * [ ]  With the new approach the name column(first column) should not grow anymore(only mobile). It should just shrink to the content. Basically default table functionality. This is the case on some pages (assets) but not the case on the bookings index. Should be consistent. Also please check all indecies because in the categories index, for example, the description column grows. Again we dont want that on mobile, just desktop.
> * [ ]  The gradient is a bit too thin(change to 35px). Also the gradient at the left point has to be 100% transparent so we have a smooth transition. Now it looks like a cut-off line
> * [ ]  The gradient should only be there if the table is overflowing horizontally(both desktop and mobile). For example in the Non-registered members index, there are very few columns so they fit and there is no horizontal scroll, however there is still a gradient covering the right column
> * [ ]  team/users index still has the chevrons, even tho it has the new style of table. Needs to be adjusted
> * [ ]  Booking/manage-assets modal is basically broken now. I cant scroll it or view it. Same for location/manage-assets modal.

resolved all the issues. i am not 100% sure about the gradient(CSS background thing. i might need help on that).

2024-08-21 19:32 UTC, rajeshj11 commented
> * [ ]  Batch Action is broken on Mobile (Safari) - On Asset Index it works well
> 
> Perhaps adjacently related:
> 
> On asset dashboard - some widgets seem to assume they are side-scroll-able and therefore show some sort of shadow on the right side.
> 
> Same as locations on mobile. Action panel looks broken.
> 
> Calendar component also seems to be cracking.
> 
> User table on mobile seems to also show the right pointing chevron to show its click-able but also sidescroll.
> 
> @DonKoko my comments.
> 
> ![IMG_7759](https://private-user-images.githubusercontent.com/12449255/359982919-9992047c-bae4-4a7d-baee-99300a4c1f11.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNjg3NTcsIm5iZiI6MTcyNDI2ODQ1NywicGF0aCI6Ii8xMjQ0OTI1NS8zNTk5ODI5MTktOTk5MjA0N2MtYmFlNC00YTdkLWJhZWUtOTkzMDBhNGMxZjExLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDE5MjczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ODI2NWJiMTdhMDZmYTA1ZGVjMGU1Y2ZiNjcyZDQ1Mjc4NGMzYWVkOWM2MWIzNjY3ZTU4ZDMwZGIwMTU2YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qUgVLZP_qpJYe28_kk6rurr2NzMX_RJs2DWR8PH8NvE)

I am not sure about the calendar thing. @DonKoko I have checked with main branch it is same. other issues were taken care.

2024-08-22 08:13 UTC, DonKoko requested changes
- [ ] with the new approach, the description column on categories index should not be truncated in 1 row. Can you make it that it takes 3 rows. We have a function alreayd in shelf that counts the rows and truncates the text

For the gradient do the following:
1. Increase width to 35px
2. Set the gradient to : `linear-gradient(to right, rgba(255, 255, 255, 0) 0%, #fff 100%)`

2024-08-22 08:14 UTC, rajeshj11 commented
> * [ ]  with the new approach, the description column on categories index should not be truncated in 1 row. Can you make it that it takes 3 rows. We have a function alreayd in shelf that counts the rows and truncates the text
> 
> For the gradient do the following:
> 
> 1. Increase width to 35px
> 2. Set the gradient to : `linear-gradient(to right, rgba(255, 255, 255, 0) 0%, #fff 100%)`

ack

2024-08-22 08:26 UTC, carlosvirreira commented
What I meant about the calendar.

![IMG_7762](https://github.com/user-attachments/assets/d22dee65-317f-4bfd-9494-9a63698cdabe)

Besides that, looks good to me (safari, iPhone)

2024-08-22 10:35 UTC, DonKoko requested changes

2024-08-22 10:35 UTC, DonKoko commented on app/components/table.tsx
> +    window.addEventListener("resize", checkOverflow); // Check on resize
If you want to do this, inside the useEffect you should have a `if (window)`

2024-08-22 10:35 UTC, DonKoko commented on app/components/table.tsx
> +  useEffect(() => {
Can you please abstract this into its own hook called `useTableIsOverflowing` which returns the value?

2024-08-22 11:18 UTC, DonKoko approved these changes

2024-08-22 11:20 UTC, merged