fix: overflow issue of kit name in asset overview page
Shelf-nu/shelf.nu pull request #1360
Opened 2024-10-16 14:16 UTC by rajeshj11

2024-10-16 14:32 UTC, rajeshj11 commented
![Uploading Screenshot from 2024-10-16 20-02-15.png…]()

2024-10-17 09:39 UTC, DonKoko requested changes
This works good, but we still have the other case.
If you add the kit with the very long name to a booking, and then check the booking page you can see the issue:
![image](https://github.com/user-attachments/assets/538851bc-422b-4deb-9dc3-12ffccbbc498)
![image](https://github.com/user-attachments/assets/446152e2-71e3-42cc-a2a8-16e6b260b203)
You can see in the second screenshot. Its the link that is causing the issue. Should be `items-start` and truncated as well.

2024-10-17 09:49 UTC, rajeshj11 commented
> This works good, but we still have the other case. If you add the kit with the very long name to a booking, and then check the booking page you can see the issue: ![image](https://private-user-images.githubusercontent.com/7840007/377406366-538851bc-422b-4deb-9dc3-12ffccbbc498.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNTg4MzgsIm5iZiI6MTcyOTE1ODUzOCwicGF0aCI6Ii83ODQwMDA3LzM3NzQwNjM2Ni01Mzg4NTFiYy00MjJiLTRkZWItOWRjMy0xMmZmY2NiYmM0OTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTdUMDk0ODU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjE4NGVmYmYyYWYyODI1YTIyMWU1NTlhYmUyZTM2ZmM3YjRhNTdlYjRiODExZGE1OTlmMTczOWMxNDJlZWIzMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.BEFimRRzABbnGkyuxOpxpwQWLTAmO2NKzhrp0_Yjo_c) ![image](https://private-user-images.githubusercontent.com/7840007/377406889-446152e2-71e3-42cc-a2a8-16e6b260b203.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNTg4MzgsIm5iZiI6MTcyOTE1ODUzOCwicGF0aCI6Ii83ODQwMDA3LzM3NzQwNjg4OS00NDYxNTJlMi03MWUzLTQyY2MtYTJhOC0xNmU2YjI2MGIyMDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTdUMDk0ODU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWUxMjRjZmQzOGM0NjZkNTg3ZmNlODZiMTIxMGNjMjg2ZDkwNjU0OWY0N2UyNWI3OTIzY2UyNDZiYTc0YjM2MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.5URESJAAFa8bV9s2F8sGfyiQ0z3jqUuSm7Xos4t4k-o) You can see in the second screenshot. Its the link that is causing the issue. Should be `items-start` and truncated as well.

will work on it

2024-10-18 10:08 UTC, DonKoko approved these changes

2024-10-18 10:10 UTC, merged