feat: add assest and kits to exisiting booking
Shelf-nu/shelf.nu pull request #1364
Opened 2024-10-18 19:08 UTC by rajeshj11

2024-10-21 07:02 UTC, rajeshj11 commented
@DonKoko please review

2024-10-21 11:56 UTC, DonKoko commented on app/routes/_layout+/kits.$kitId.tsx
This route should be a child of the asset overview route so when it opens you can still see the asset behind.

2024-10-21 11:58 UTC, DonKoko commented on app/components/assets/actions-dropdown.tsx
> +export const BookActionsDropDown = () => {
I am very very confused by the placement of this component. Why not in the file with the other relevant components or maybe in its own file?

2024-10-21 11:59 UTC, DonKoko commented on app/utils/booking-drop-down-actions.tsx
This is a component file. Should not be placed here but rather in the correct folder in components.

2024-10-21 11:59 UTC, DonKoko commented on app/utils/booking-drop-down-actions.tsx
> +  const disabled_reason = links.find((link) => link.disabled)?.disabled_reason;
camelCase please

2024-10-21 12:16 UTC, DonKoko commented on app/routes/_layout+/bookings.update-existing.tsx
> +      z.object({
Please make the code more modular and extract this into a Schema variable. We only do it inline when its super simple schema and this is not the case here.

2024-10-21 12:16 UTC, DonKoko commented on app/routes/_layout+/bookings.update-existing.tsx
> +          <p>You can only add an asset to bookings that</p>
No need to split this in 2 paragraphs.

2024-10-21 12:17 UTC, DonKoko commented on app/routes/_layout+/bookings.update-existing.tsx
> +        {tab === "assets" &&
I am a bit confused by the variable name `tab`. There are no tabs in this UI. When someone just looks at this code this variable name will make it very confusing for them on why and what the UI is. Please use something more descriptive of the value that is being stored.

2024-10-21 12:38 UTC, DonKoko commented on app/routes/_layout+/bookings.update-existing.tsx
> +const getAvailableAssets = async (assetIds: string[]): Promise<string[]> => {
This function should not be in this file.
Also why not just use `getAssets`?

2024-10-21 12:39 UTC, DonKoko commented on app/routes/_layout+/bookings.update-existing.tsx
> +  if (finalAssetIds.length === 0) {
This should not happen and should be controlled at an earlier step of the process.
To start with, the button should be disabled if the kit has no assets inside it.

2024-10-21 12:40 UTC, DonKoko commented on app/routes/_layout+/bookings.update-existing.tsx
> +    function intersected(arr1: string[], arr2: string[]): boolean {
Please place this in the correct place. This is a very useful function. Placing it here only within this loader seems like a huge waste.

2024-10-21 12:58 UTC, DonKoko commented on app/routes/_layout+/bookings.update-existing.tsx
> +          <DynamicSelect
I would have never done this with the DynamicSelect, would have just made something simple. This works now so its fine, maybe a bit of an overkill but we will see. My main concern is that you had to adjust the model-filters which now means we are required to test like 10 different features.

2024-10-21 12:59 UTC, DonKoko commented on app/routes/_layout+/bookings.update-existing.tsx
> +                  <h3 className="max-w-[250px] truncate">{item.name}</h3>
This is way too huge. Should be just a div with 16px font size and semibold and the dates below should be font size 14px.

2024-10-21 13:05 UTC, DonKoko commented on app/routes/_layout+/bookings.update-existing.tsx
> +const getBookingDetails = async (
I see you added 4 functions in this file that I feel are just repeating existing stuff and can be managed way better.

1. They should not be in this file. Each function should be in the relevant service file for the model it refers to
2. All function should have a try/catch.

2024-10-23 06:44 UTC, rajeshj11 commented
@DonKoko can you please review

2024-10-24 08:07 UTC, rajeshj11 commented
@DonKoko does it still need work? please let me know.

note: As we already discussed in Discord.
if you think the pr is overkill. we can simply close it. no issues

2024-10-24 09:56 UTC, DonKoko requested changes
Already way better but still some changes pending.

2024-10-24 09:56 UTC, DonKoko commented on app/components/shared/actions-drop-down.tsx
`dropdown` instead of `drop-down` in file name

2024-10-24 09:56 UTC, DonKoko commented on app/modules/asset/service.server.ts
> +  } catch (err) {
Please use `cause`. that is what we use everywhere. Also the message in the catch should be dynamic. something like this:
```ts
message: cause?.message ? cause.message : "some message"
```

2024-10-24 09:56 UTC, DonKoko commented on app/modules/booking/service.server.ts
> +      message: "Something went wrong while getting existing booking details.",
Dynamic message from cause.

2024-10-24 09:56 UTC, DonKoko commented on app/modules/booking/service.server.ts
> +    const booking = await db.booking.findFirst({
Usually we use `findUniqueOrThrow` as this automatically handles 404s. Is there some specific reason to not use it here.

2024-10-24 09:56 UTC, DonKoko commented on app/modules/kit/service.server.ts
> +      message: "Something went wrong while getting available assets.",
Dynamic message from cause./

2024-10-24 09:56 UTC, DonKoko commented on app/routes/_layout+/assets.$assetId.tsx
> +        <BookingActionsDropDown />
`BookingActionsDropdown` instead of `BookingActionsDropDown`

2024-10-24 09:56 UTC, DonKoko commented on app/routes/_layout+/bookings.update-existing.tsx
> +  } catch (err) {
Use `cause` please. Also use the message from the cause if it exists. That way the user knows what actually happened.

2024-10-24 09:56 UTC, DonKoko commented on app/routes/api+/model-filters.ts
> +    const genericKeys = ["deletedAt"];
I am having trouble understanding this. Can you explain why you are doing it and add some annotations. Then we can maybe see if there is a better way to manage it.

2024-10-24 09:56 UTC, DonKoko commented on app/components/assets/booking-actions-dropdown.tsx
> +    <div className="actions-dropdown flex">
Although this works, that is now what we wanted to achieve. Please look at the example we gave.
It is not a singular dropdown, its a button group where the left item is the main button and the right item is a dropdown trigger with the different options. Let me know if you need further examples.

2024-10-25 14:34 UTC, DonKoko requested changes
Files are still not as I like them

2024-10-25 14:34 UTC, DonKoko commented on app/routes/_layout+/bookings.update-existing.tsx
File name is too generic. It needs to be more specific to what it does. Also this should be a child of `assets.$assetId.overview`. Please name the file: `assets.$assetId.overview.add-to-existing-booking`

Then you would need to create also a file in `kits.$kitId.add-to-existing-booking`

And last you can create a function for the action, loader & component so you can use them in the 2 different places.

2024-11-04 14:57 UTC, rajesh-jonnalagadda commented
@DonKoko Could you please review this when you have some time? It’s been pending for a while.

2024-11-04 14:58 UTC, rajesh-jonnalagadda commented
> @DonKoko Could you please review this when you have some time? It’s been pending for a while.

if not needed please close it. i can understand

2024-11-05 11:15 UTC, DonKoko reviewed
I made a lot of changes myself to optimize, cleanup and change stuff that were not used as we usually do. We are now in the process of testing this on our staging env.

2024-11-05 13:50 UTC, carlosvirreira commented
From my test / Observation:

- If an asset is marked as unavailable for booking. Please make the dropdown button disabled. "The asset is marked as unavailable for booking - please adjust this to proceed"
- 
![Screenshot 2024-11-05 at 14 49 54](https://github.com/user-attachments/assets/af634865-3240-4b6e-aeed-58832c5f8dc9)

2024-11-06 10:09 UTC, DonKoko commented
Thanks @carlosvirreira . I will resolve it.

2024-11-06 10:50 UTC, DonKoko approved these changes

2024-11-06 10:59 UTC, merged