Added dropdown in booking page assets management
Shelf-nu/shelf.nu pull request #1370
Opened 2024-10-25 02:39 UTC by vikashsprem

Closes #1368
/claim #1368

Uploading Screen Recording 2024-10-25 at 8.01.37 AM.mp4…

2024-10-25 02:40 UTC, vikashsprem commented
@carlosvirreira Please review.

2024-10-25 09:44 UTC, DonKoko requested changes
Great first PR. I have added some feedback with some changes needed to make it more fitting to our normal coding style in shelf.

2024-10-25 09:44 UTC, DonKoko commented on app/components/booking/booking-assets-column.tsx
> +    setExpandedKits((prev: any) => ({
No need to use any. You have the type defined above.

2024-10-25 09:44 UTC, DonKoko commented on app/components/booking/booking-assets-column.tsx
> +  const [categoryVisibility, setCategoryVisibility] = useState<number>(0);
Can you please annotate this, so when another developer opens they can know directly what `categoryVisibility` refers to.

2024-10-25 09:44 UTC, DonKoko commented on app/components/booking/booking-assets-column.tsx
> +                              <ListItem key={asset.id} item={asset}>
Can you please animate them with framer. 1 thing you might have to slightly adjust the `ListItem` to use use `motion.tr` and receive optional animation props. Needs some testing I am not 100% sure exactly what the right approach would be.

2024-10-25 09:44 UTC, DonKoko commented on app/components/booking/booking-assets-column.tsx
> +                                  className="text-center font-bold"
Please use `text-gray-600` so the icon inherits it and its not orange.

2024-10-25 09:44 UTC, DonKoko commented on app/components/booking/booking-assets-column.tsx
> +                                    <ChevronUpIcon className="size-6" />
This works but its not how we usually do it. You can just use `ChevronDownIcon` and then use `tw()` helper to dynamically add a rotate class based on `isExpanded`. That way you can also add a css animation to it.

2024-10-25 11:48 UTC, DonKoko requested changes
- [ ] When items are folded its strange they dont have a border between them:
<img width="812" alt="Screenshot 2024-10-25 at 14 42 28" src="https://github.com/user-attachments/assets/88ed2c77-8e82-473a-9b6c-8be8a140c502">
- [ ] Same when I hover an item. We need to address those cases to make the UI consistent
<img width="806" alt="Screenshot 2024-10-25 at 14 42 36" src="https://github.com/user-attachments/assets/460b8a83-9d70-4698-8dd8-1e91cf2001fa">
- [ ] Hover of arrow should be `text-gray-500`. Now it becomes orange which is wrong.
<img width="240" alt="Screenshot 2024-10-25 at 14 43 16" src="https://github.com/user-attachments/assets/d48cce3e-7444-42c2-a6c0-817a6a4e2ebe">
- [ ] Lets make the default state to be "open"

2024-10-25 11:48 UTC, DonKoko commented on app/components/booking/booking-assets-column.tsx
> +                                whileHover: { scale: 1.02 },
This causes a bug in the UI. Please remove the tap and hover effects.

2024-10-28 10:17 UTC, DonKoko approved these changes

2024-10-28 10:20 UTC, merged

2024-10-28 10:20 UTC, DonKoko commented
@vikashsprem I just had to make some changes to the borders. Thanks for the PR.

2024-10-28 11:38 UTC, carlosvirreira commented
Nice, I've seen it on live. Good improvement. Thank you both!