Improvement to Calendar View
Shelf-nu/shelf.nu pull request #1392
Opened 2024-11-05 15:12 UTC by Bhavyajain21

fixes #1350

2024-11-05 15:14 UTC, Bhavyajain21 commented
![image](https://github.com/user-attachments/assets/bd786fcf-69b2-4f52-807e-1e986c6aa80d)

2024-11-06 13:26 UTC, DonKoko requested changes
I have done some testing, there are the things I noticed so far:
- [x] There should be an active state for the currently active view. You can check the simple & advanced buttons on the asset index for example on how the active state should look. It should basically be the same as the current hover effect
<img width="500" alt="Screenshot 2024-11-06 at 15 18 23" src="https://github.com/user-attachments/assets/22acd845-3378-47fe-8462-114eb5e52013">

- [ ] The title should be updated when the mode is changed. Here is how it should work:
<img width="591" alt="Screenshot 2024-11-06 at 15 19 43" src="https://github.com/user-attachments/assets/30cf619b-2069-469b-8afd-d22802970f62">

1. Month - keep as is
2. Week - Keep as is + add a subtitle saying "Week ${week start day} - ${week end date}"
3. Day - Prepend the date to the month + year. Add subtitle with the week day.


- [ ] When we are in day view, dont highlight in orange the whole day
- [x] In day view, when there are multiple events the UI breaks:
<img width="983" alt="Screenshot 2024-11-06 at 15 24 14" src="https://github.com/user-attachments/assets/12c41fbb-d038-4e95-a024-9c1619e075c2">

- [ ] in week view, having multiple events looks broken

<img width="667" alt="Screenshot 2024-11-06 at 15 25 17" src="https://github.com/user-attachments/assets/f7263ebe-8a50-4c8d-961e-29885c0b9e77">

2024-11-14 10:05 UTC, carlosvirreira commented
@DonKoko if you pull this, could you send me a screenshot(s)?

2024-11-14 12:48 UTC, DonKoko requested changes

2024-11-14 12:48 UTC, DonKoko commented on app/routes/_layout+/calendar.tsx
> +    if (view === "dayGridMonth") {
why not just:
`updateTitle(view)`. The `if` block seems redundant.

2024-11-14 12:48 UTC, DonKoko commented on app/routes/_layout+/calendar.tsx
> +  const [calendarView, setCalendarView] = useState(
This is problematic. Let me explain.
This will run every time the component re-renders.
So if you have the following scenario:

1. Switch to day view
2. Resize window
3. Component re-renders
4. You see month view but on the buttons day view is selected.

This needs to be updated on how we set the default one. You have have a `useEffect` that runs on render that updates the value based on the screen size + the current selected value.

2024-11-14 12:48 UTC, DonKoko commented on app/routes/_layout+/calendar.tsx
>              <ButtonGroup>
Should not be visible on mobile. Only view allowed on mobile is list.

2024-11-17 16:13 UTC, Bhavyajain21 commented on app/routes/_layout+/calendar.tsx
> +    if (view === "dayGridMonth") {
Fixed!

2024-11-17 16:13 UTC, Bhavyajain21 commented on app/routes/_layout+/calendar.tsx
> +  const [calendarView, setCalendarView] = useState(
This is fixed with a small change

2024-11-17 16:13 UTC, Bhavyajain21 commented on app/routes/_layout+/calendar.tsx
>              <ButtonGroup>
Fixed

2024-11-19 12:13 UTC, DonKoko requested changes
- [ ] currently, when hovering an event the info shows up only when hovering the name. Should be for hovering the whole block
![image](https://github.com/user-attachments/assets/934cbad5-b75b-4338-b1ae-49838072cc1a)
- [ ] currently single day events only have a bg-color on hover. This should be the case only for monthly view. In the other views, they should always have the events
- [x] The dot for 1 day events should only be visible on monthly view:
![image](https://github.com/user-attachments/assets/91cf333a-9453-4c31-8bbb-4d013bd84e51)
- [x] On week view, the title is still not correct. Please check how we do it on mobile. It should be 1:1 with how we do it there
- [x] Currently when you have 2 events overlapping on the same time, they are kinda squashed next to eachother. This makes it ugly and very condensed. What we want to do is make it like it is in the example on full calendar or as a matter of fact like in any calendar app. My example I use is the apple calendar app.
**Currently looks like:**
![image](https://github.com/user-attachments/assets/0d08b997-6023-4a0d-80c4-112f8e802deb)

**Should look like:**
![image](https://github.com/user-attachments/assets/bba61488-c015-4a20-917d-3d925f897305)

Please check the full calendar docs for this. Just quickly searched and found this: https://fullcalendar.io/docs/slotEventOverlap. You have set this to false, not sure why.

- [x] When I go on day view and I go to "Today" the whole day is still highlighted. This should not be the case for the day view, only for month/week.
- [x] When events are overlapping, we should figure out how to add a shadow to the events that are on top of other events. From what I can see FullCalendar adds a z-index to `fc-timegrid-event-harness` so we could somehow style based on this. You can just use one of the shadows we have available in tailwind.

2024-11-19 12:25 UTC, DonKoko commented
I am gonna add another comment related to the overlapping because I found something cool I wanted to share. Take a look at this video:

https://github.com/user-attachments/assets/255b52bc-184d-4116-87c8-0217d4257e19

2024-11-25 12:13 UTC, DonKoko requested changes
- [ ] When the event is very short there is not enough space to show the text. I am wondering if FullCalendar has some way to manage this. Could you check it out please
![image](https://github.com/user-attachments/assets/c88e8940-c5f8-4edb-80c3-b9965aa44809)
![image](https://github.com/user-attachments/assets/1efba348-79c4-4c0d-8f21-6362c7de0efb)

- [ ] 1 day event background color has been added also to month view. The idea was to add it only to the other views (week & day)

2024-11-29 12:50 UTC, merged