Docs improvement
Shelf-nu/shelf.nu pull request #316
Opened 2023-08-24 06:27 UTC by hrutik7

2023-08-24 06:39 UTC, hrutik7 commented
#311

2023-08-24 12:34 UTC, DonKoko requested changes
Thanks a lot for the pr @hrutik7. Everything is good, I just took the time to read what we have and made some small requests for changes. 
Also, could you please add a README.md inside the docs folder where we can just write a 1-2 sentence introduction and place a table of contents, linking to the subfiles in the docs folder.

2023-08-24 12:34 UTC, DonKoko commented on README.md
> +    <a href="https://www.shelf.nu/"><b>Website</b></a> •
Please add `?ref=github`

2023-08-24 12:34 UTC, DonKoko commented on README.md
> +<p align="center">
I think all those links should open in a new tab.

2023-08-24 12:34 UTC, DonKoko commented on README.md
> +    <a href="https://github.com/Shelf-nu/shelf.nu"><b>Documentation</b></a> •
Lets add `/docs`. We don't have it now but as soon as we merge this it will be there so we are good.

2023-08-24 12:34 UTC, DonKoko commented on docs/get-started.md
> +# Remix Supa Fly Stack
Lets remove this part. We are giving reference to supa-fly-stack in the section above. So like 10:17 need to be removed.

2023-08-24 12:34 UTC, DonKoko commented on docs/get-started.md
> +Not a fan of bits of the stack? Fork it, change it, and use `npx create-remix --template your/repo`! Make it your own.
Please remove this line.

2023-08-24 16:37 UTC, hrutik7 commented on README.md
> +<p align="center">
I added this one as well as ?ref=github too but it's not opening in new tab

2023-08-25 02:39 UTC, hrutik7 commented on README.md
> +    <a href="https://www.shelf.nu/"><b>Website</b></a> •
Are you sure on this ? because generally README.md file is in the root folder

2023-08-25 08:39 UTC, DonKoko commented on README.md
> +<p align="center">
> I added this one as well as ?ref=github too but it's not opening in new tab

Okey thats fine. Maybe github has some limitations related to this.

2023-08-29 11:32 UTC, DonKoko approved these changes
Looks good. Thanks for updating it as we discussed and for opening the PR.

2023-08-29 11:48 UTC, DonKoko approved these changes

2023-08-29 11:49 UTC, merged