[wip] add additional custom field support
Shelf-nu/shelf.nu pull request #365
Opened 2023-09-15 22:23 UTC by mahendraHegde

closes #307

2023-09-26 13:00 UTC, DonKoko requested changes
I have a few small changes required.

2023-09-26 13:00 UTC, DonKoko commented on app/components/assets/custom-fields-inputs.tsx
> +  const [dateObj, steDateObj] = useState(customFieldsValues.filter(v => v.value.valueDate).reduce((res, cur) => {
Small spelling mistake. Should be `setDateObj`

2023-09-26 13:00 UTC, DonKoko commented on app/database/migrations/20230919162512_expand_custom_fields/migration.sql
> +ALTER TABLE "AssetCustomFieldValue"
Can you explain that a bit further. I would like to understand exactly what we are doing here.

2023-09-26 13:00 UTC, DonKoko commented on app/routes/_layout+/assets.$assetId.tsx
> +                      <div className="max-w-[250px]">{getCustomFieldDisplayValue(field.value as unknown as ShelfAssetCustomFieldValueType["value"])}</div>
Lets align the multiline text to the right.
<img width="434" alt="Screenshot 2023-09-26 at 15 24 10" src="https://github.com/Shelf-nu/shelf.nu/assets/7840007/2c76afb0-ca00-42e0-bee7-b03c3ae0b3f4">

2023-09-26 13:00 UTC, DonKoko commented on app/components/assets/import-content.tsx
> +        To import custom fields, prefix your column heading with <b>"cf: "</b>, add the type followed by a coma from one of the allowed types(<b>"text", "boolean", "option", "multiline text", "date"<
This is a good explanation but I think we need to write a blog post with more details about this. @carlosvirreira 
@mahendraHegde also I am wondering how does it work with options?

2023-09-26 13:04 UTC, mahendraHegde commented on app/components/assets/import-content.tsx
> +        To import custom fields, prefix your column heading with <b>"cf: "</b>, add the type followed by a coma from one of the allowed types(<b>"text", "boolean", "option", "multiline text", "date"<
for options, we check if the custom field and option both exists, if not we create them, if only option is new, we add the new option to the existing custom field

2023-09-26 13:06 UTC, DonKoko commented on app/components/assets/import-content.tsx
> +        To import custom fields, prefix your column heading with <b>"cf: "</b>, add the type followed by a coma from one of the allowed types(<b>"text", "boolean", "option", "multiline text", "date"<
Maybe good to also add that to the explanation in you added.

2023-09-27 09:20 UTC, DonKoko commented
Tests are failing because I didnt update them to use node-18 yet. I will merge the PR with the tests failing and will then fix it in dev so it can be deployed. Will also be adjusted in main branch.

2023-09-27 09:20 UTC, merged

2023-09-27 09:23 UTC, DonKoko commented
@mahendraHegde did you solve the issue with `eslint-plugin-unused-imports`? I still cant install it on node-18.