created a default value field for assets
Shelf-nu/shelf.nu pull request #455
Opened 2023-10-13 11:57 UTC by hunar1312

resolves #436

2023-10-13 13:53 UTC, DonKoko requested changes
Added some comments. Mostly small changes.

2023-10-13 13:53 UTC, DonKoko commented on app/database/migrations/20230428075403_add_qr_to_db/migration.sql
> -
We removed this for testing purposes when we were checking the issue you had. There should be no changes in this file. Please revert them

2023-10-13 13:53 UTC, DonKoko commented on app/routes/_layout+/assets.$assetId.tsx
> +  const organization = await getOrganizationByUserId({
I dont think you need to do that. You can just adjust the query for asset by including organization and selecting only the currency field.
Something like this. 
```
include: {
  organization: {
    select: {
      currency: true
     },
  }
}
```

and then u can do `asset.organization.currency`

2023-10-13 13:53 UTC, DonKoko commented on app/routes/_layout+/assets.new.tsx
> +        <AssetForm qrId={qrId} currency={currency} />
Not sure why we are passing the currency here. It comes from the loader, just get it inside the asset form itself.

2023-10-16 08:52 UTC, DonKoko requested changes
So far so good, however we are missing some stuff.

- [x] displaying value on asset page
- [ ] Setting default currency

The first part you can do now already, but the second part is a bit tricky, as it has to be an option on workspace, but we are still working on the workspaces/organizations, so I think we have to wait for it to be merged before we can merge this as if we dont wait it will create db and code conflicts and its just not worth it. Lets resolve the first one and then mark this as blocked by #369

2023-10-16 08:56 UTC, hunar1312 commented
https://github.com/Shelf-nu/shelf.nu/pull/455/files#diff-6abae98ca8769c62228e2e3bed3a8388223caed03c9c1aab378bbb4b46e95d15 the first part is already done @DonKoko and we already discussed that we won't move froward till the organization's page is refactored. So yeah we gotta put hold on this one for now.

2023-10-16 09:14 UTC, DonKoko commented
@hunar1312 yeah i also did some more testing and I realized we are really blocked by the organization refactoring so we have to wait before we can merge it.

2023-11-01 16:13 UTC, DonKoko commented
@hunar1312 updated the PR by merging it with main. There are some changes that will need to be done and you will get some TS errors so better solve them first. Some of the types are moved to a different file as well as now everything is scoped with organizationId instead of userId.

2023-11-06 14:13 UTC, DonKoko commented
@hunar1312 I have updated the branch with main. Here is what is still pending:

- [ ] code needs to be updated to use organizationId instead of userId for scoping of everything. I believe TS should already give you errors on those places where orgId is missing because its required.
- [ ] We have a view for editing workspaces. We should add a field where they can change workspace currency.

2023-11-13 16:25 UTC, DonKoko approved these changes

2023-11-13 16:25 UTC, merged