feat: Implement "uncategorized" for assets
Shelf-nu/shelf.nu pull request #469
Opened 2023-10-19 15:36 UTC by vineetjk

## Completed tasks in this feature

fixes #450 

- [x] Default category as `Uncategorised` while creating new asset
![image](https://github.com/Shelf-nu/shelf.nu/assets/42497152/64d03634-c2e9-4050-ab11-cbf70758e776)

- [x] Created `Uncategorised` badge in asset index page
![image](https://github.com/Shelf-nu/shelf.nu/assets/42497152/b285c58d-8239-4184-ba9c-e8c1f624968b)

- [x] Created `Uncategorised` badge in single asset page
![image](https://github.com/Shelf-nu/shelf.nu/assets/42497152/6dc215c3-90f1-440f-9db0-97bf60709777)

- [x] Added `Uncategorised` to categories filter
![image](https://github.com/Shelf-nu/shelf.nu/assets/42497152/9b21da29-03a3-4e31-95af-10d44e881e08) 
![image](https://github.com/Shelf-nu/shelf.nu/assets/42497152/0f8970db-0de3-4e7c-bcb9-574b8a7f544a)

- After applying Uncategorised` filter in index page
![image](https://github.com/Shelf-nu/shelf.nu/assets/42497152/627cb99c-22d6-40cc-9b6e-f56915897471)

2023-10-20 11:02 UTC, DonKoko requested changes
Okey so overall good, however a few issues

1.  If you try to "clear" (set to uncategorized) the category of an item that already has one assigned it will fail. This case needs to be handled. Basically if the category is `uncategorized` when editing an asset, we have to disconnect the category connected to that asset.

2. Seems like you have some different formatting options on your system or something so lots of stuff got their spacing and formatting adjusted which should not happen. Please solve this. If you dont have it, you can install prettier and that should format it properly as we have `.prettierrc.json` setup.

2023-10-20 14:03 UTC, vineetjk commented
> Okey so overall good, however a few issues
> 
> 1. If you try to "clear" (set to uncategorized) the category of an item that already has one assigned it will fail. This case needs to be handled. Basically if the category is `uncategorized` when editing an asset, we have to disconnect the category connected to that asset.
> 2. Seems like you have some different formatting options on your system or something so lots of stuff got their spacing and formatting adjusted which should not happen. Please solve this. If you dont have it, you can install prettier and that should format it properly as we have `.prettierrc.json` setup.

Issues are resolved.

2023-10-20 14:32 UTC, DonKoko approved these changes

2023-10-20 14:33 UTC, merged

2023-10-23 09:04 UTC, DonKoko commented
hey @vineetjk . I had to unfortunately revert those changes because we had some crashes in live.
So I checked it and I noticed that we have different places where we update asset, we dont only do it in the updateAsset form. You can for example check the file `refresh-main-image`.

So we need to adjust how the update function works. WE will have cases when we are updating and we are not passing a `categoryId` but we dont want the category to be disconnected.

Maybe what you can try is to use `null`.
So if `categoryId` is:
- `undefined` - we dont do anything
- `null` - we disconnect. 

Then we will have to simply make sure that the value of `categoryId` when updating an asset and setting the category to `Uncategorized` is passed as `null`.

Please also search around the codebase and see for other places we are updating asset, as we have to also consider it there. I took a quick look and there is a few places where we use `updateAsset` so they all have to be tested.