feat:Generating a PDF with booking overview #942
Shelf-nu/shelf.nu pull request #999
Opened 2024-05-28 10:24 UTC by rajeshj11

Added pdf generator for booking review

demo video:
https://www.loom.com/share/7817717d84134914b45d2bc4d841b659

note: right now considering all the bookings have this feature.(even draft)

2024-05-28 14:02 UTC, DonKoko requested changes
Okey so overall your PR is really nice man, especially for a first PR working with shelf, however I dont like the ejs approach. It introduces another thing and i would rather for the most part use the tools we already have. So my suggestion is to use the approach of Sergio:  https://sergiodxa.com/tutorials/generate-a-pdf-in-remix-with-resource-routes

Here is how I would handle it step by step: 
1. Create a PDFReport component which we render inside the alert dialog(where we are currently showing the iframe).
2. We can then style this component using our existing tools and 
3. Update the resource route that you have made to actually work like in the example above with `renderToStream` from `"@react-pdf/renderer"` and use the same component we are previewing above
4. The download button should then be a link to that resource route which will trigger a download.

Also I think we should create a function that fetches the DB and gets us all the data we need for this, kind of like in the example. So the loader is very clean.

Let me know on discord if you have any questions.

2024-05-28 14:02 UTC, DonKoko commented on app/components/booking/generate-booking-pdf.tsx
> +    window.location.href = url;
Remix has ways to handle navigation that I would rather use than this. Check out the hook `useNavigation`.

2024-05-28 14:02 UTC, DonKoko commented on app/modules/qr/service.server.ts
> +            qr = await createQr({ assetId, userId, organizationId });
That should not be needed and will never happen. An asset cannot be without a QR code.

2024-05-28 14:02 UTC, DonKoko commented on app/components/booking/generate-booking-pdf.tsx
> +export const GenerateBookingPdf = ({ booking }: { booking: any }) => {
We dont use `any`. This should be properly typed.

2024-05-29 18:41 UTC, DonKoko commented
@rajeshj11 congrats on the PR. This I am way happier with than what we had before with ejs. I have deployed it to our staging env so the rest of the team can test it. I still have to review the files but I am doing that already.

2024-05-30 12:57 UTC, rajeshj11 commented
Will look into it

On Thu, 30 May 2024, 17:51 Nikolay Bonev, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Unfortunately it still doesn't work on staging/production server.
>
> {
>   "level": 50,
>   "time": 1717071514317,
>   "pid": 336,
>   "hostname": "4d890e36c76798",
>   "err": {
>     "cause": {
>       "stack": "Error: Browser was not found at the configured executablePath (/usr/bin/google-chrome-stable)\n    at ChromeLauncher.launch (file:///src/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:46:19)\n    at async generatePdfContent (file:///src/build/server/remix.js:21558:19)\n    at async loader$U (file:///src/build/server/remix.js:21609:23)\n    at async Object.callRouteLoaderRR ***@***.***/server-runtime/dist/data.js:52:16)\n    at async callLoaderOrAction ***@***.******@***.***/router/dist/router.cjs.js:4166:16)\n    at async Promise.all (index 0)\n    at async loadRouteData ***@***.******@***.***/router/dist/router.cjs.js:3638:19)\n    at async queryImpl ***@***.******@***.***/router/dist/router.cjs.js:3481:20)\n    at async Object.queryRoute ***@***.******@***.***/router/dist/router.cjs.js:3447:18)\n    at async handleResourceRequestRR ***@***.***/server-runtime/dist/server.js:296:20)"
>     },
>     "label": "Unknown",
>     "additionalData": {
>       "userId": "28babcf6-d37e-4cfc-9d39-097e973de068",
>       "bookingId": "clvnowg52006hhmba8us2gga4"
>     },
>     "shouldBeCaptured": true,
>     "status": 500,
>     "traceId": "zfsagzjk1ieos07sgg223n75",
>     "name": "ShelfError",
>     "message": "Sorry, something went wrong.",
>     "stack": "ShelfError: Sorry, something went wrong.\n    at makeShelfError (file:///src/build/server/remix.js:122:10)\n    at loader$U (file:///src/build/server/remix.js:21620:20)\n    at async Object.callRouteLoaderRR ***@***.***/server-runtime/dist/data.js:52:16)\n    at async callLoaderOrAction ***@***.******@***.***/router/dist/router.cjs.js:4166:16)\n    at async Promise.all (index 0)\n    at async loadRouteData ***@***.******@***.***/router/dist/router.cjs.js:3638:19)\n    at async queryImpl ***@***.******@***.***/router/dist/router.cjs.js:3481:20)\n    at async Object.queryRoute ***@***.******@***.***/router/dist/router.cjs.js:3447:18)\n    at async handleResourceRequestRR ***@***.***/server-runtime/dist/server.js:296:20)\n    at async requestHandler ***@***.***/server-runtime/dist/server.js:104:18)"
>   },
>   "msg": "Sorry, something went wrong."
> }
>
> Just FYI we use fly.io and the deployment works via our Docker file. Can
> you please look into it? I can imagine we have to do something specific to
> install puppetteer there.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Shelf-nu/shelf.nu/pull/999#pullrequestreview-2088121903>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJHVFCED4CWNMVFWHWNTLY3ZE4KTPAVCNFSM6AAAAABIMUBZIOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAOBYGEZDCOJQGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-06-03 10:13 UTC, jurrejansen commented
- [ ] The time of when the PDF was generated doesn't seem to be correct.
![Screenshot 2024-06-03 at 11 53 19](https://github.com/Shelf-nu/shelf.nu/assets/76112272/a822c606-d19a-4631-87fb-3defceca9733)

- [ ] The thumbnails images on the PDF should have fixed height and width and the image should be set to Cover. This to avoid images with weird dimensions breaking the table on the PDF

![Screenshot 2024-06-03 at 11 55 24](https://github.com/Shelf-nu/shelf.nu/assets/76112272/9c2d3359-55be-421c-b6f5-0d1a846eda10)

If we're going to use the vertical border lines, let's make sure they're also on the spots I marked in the screenshot. Lets also make sure there's enough padding on the cells. Looks like the first column with the numbers has a fixed width and the width doesn't get bigger when the numbers go into double digits
![Screenshot 2024-06-03 at 12 00 37](https://github.com/Shelf-nu/shelf.nu/assets/76112272/28b382b1-bc0f-4ca7-b449-1821d31b7e04)
![Screenshot 2024-06-03 at 12 02 03](https://github.com/Shelf-nu/shelf.nu/assets/76112272/44328330-7207-4563-88bf-4df26aab1b02)

- [ ] Line up the workspace logo with the rest of the content
![Screenshot 2024-06-03 at 12 04 57](https://github.com/Shelf-nu/shelf.nu/assets/76112272/ceec84dc-190b-47ba-b433-ca36f04a3474)

- [ ] For longer booking names, we can maybe shorten / truncate the booking name after a certain amount of character in the top header where it also displays generation date and page number

![Screenshot 2024-06-03 at 12 09 14](https://github.com/Shelf-nu/shelf.nu/assets/76112272/aaeb6bb6-4cc9-4e36-b660-f2b2c9305ea6)
![Screenshot 2024-06-03 at 12 13 28](https://github.com/Shelf-nu/shelf.nu/assets/76112272/0662991c-588a-4ee8-9145-4c78fd53f652)

2024-06-04 08:20 UTC, jurrejansen commented
Hi @rajeshj11 here is some more stuff

- [ ] Remove the border around workspace logo
- [ ] Using the Download button downloads a ...pdf.txt file a minute after clicking it
- [ ] There's missing a space between the booking name and generation date in the header
- [ ] Change Booking:, Custodian: and Booking period: into Booking, Custodian and Booking period
- [ ] Change font weight of Booking, Custodian and Booking period into Medium
- [ ] Change column labels into Font size: 8px and Font weight: medium
- [ ] Add corner radius of 4 to the tables

![Screenshot 2024-06-04 at 10 12 01](https://github.com/Shelf-nu/shelf.nu/assets/76112272/af14c947-5f7f-4907-85ea-85cb64d0106c)

2024-06-04 10:40 UTC, rajeshj11 commented
@jurrejansen
 Using the Download button downloads a ...pdf.txt file a minute after clicking it

1. I did understand the pdf.txt extension file. is it downloading as a txt file?(not able to replicate that. need more inputs on this like screenshots, in which device etc..)
2. Yes It will take a few minutes to download the file. when the user clicks the download button again it will hit the backend and directly download the pdf. (As I could not able to find a way to use the already generated iframe data. I have configured it like this.). please do suggest any approach we can use other than this.

2024-06-04 10:53 UTC, jurrejansen commented
HI @rajeshj11 yeah it's weird. Both on Safari and Chrome the download functionality that is part of the PDF previewer is working fine.

However the custom download button that was added in the footer of the modal is not working unfortunately.

- After clicking it takes a minute or so before something happens
- Then it look like stuff is downloading because the browser is responding
- Takes even longer before files start showing up in Finder / Explorer
- Getting a bunch of .txt and .json files

Made some recordings, in the second on you can see stuff starting to download after a while but nothing appears in Finder.

https://github.com/Shelf-nu/shelf.nu/assets/76112272/b64500cb-8dd8-4ed1-8597-0c5f94565c43

https://github.com/Shelf-nu/shelf.nu/assets/76112272/0d92f975-14a0-4084-a753-134b4b912663


[booking-checklist-2024-06-04.pdf.json](https://github.com/user-attachments/files/15550329/booking-checklist-2024-06-04.pdf.json)
[booking-checklist-2024-06-04.pdf.txt](https://github.com/user-attachments/files/15550330/booking-checklist-2024-06-04.pdf.txt)

2024-06-04 11:42 UTC, rajeshj11 commented
@jurrejansen hey, can you please check now? addressed the download issue.

2024-06-04 11:53 UTC, jurrejansen commented
@rajeshj11 Nice one, works. There's still a 5 seconds delay or something though. Maybe we can  implement a loading state of the button.

![Screenshot 2024-06-04 at 13 52 29](https://github.com/Shelf-nu/shelf.nu/assets/76112272/a3bbee62-ace4-4938-8c0f-89fe5119c230)

https://github.com/Shelf-nu/shelf.nu/assets/76112272/b97230aa-d41a-44fb-8a68-b7ce1bb35620

2024-06-04 13:40 UTC, DonKoko approved these changes

2024-06-04 13:40 UTC, DonKoko commented on Dockerfile
> +#     apt-get install -y openssl && \
Please remove this old lines and update the comment to say that it installs dependencies for Pupp, chrome and prisma

2024-06-04 13:40 UTC, merged